### ISSUE TITLE
Špatné řazení zpráv

### ISSUE THREAD

**Issue by filda44** [wykys/chateen#3]
Zprávy se v jednotlivých souborech se řadí od nejnéovější, ne od nejstarší

**Comment by wykys** [comment]
Jak rozumět tomu v souborech? O kterou kartu se jedná?

**Comment by filda44** [comment]
v exportovaných

**Comment by wykys** [comment]
Aha, takže požadavek je na pořadí zpráv při exportu?

**Comment by filda44** [comment]
ano

**Comment by wykys** [comment]
Funkce byla přidána.
